apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.serviceAccountName" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-manager-role
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
# Allow managing our CRDs
- apiGroups: ["qalisa.github.io"]
  resources: ["githubactionsecretssyncs", "githubsyncrepoes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["qalisa.github.io"]
  resources: ["githubactionsecretssyncs/status", "githubsyncrepoes/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["qalisa.github.io"]
  resources: ["githubactionsecretssyncs/finalizers", "githubsyncrepoes/finalizers"]
  verbs: ["update"]

# Allow reading Secrets and ConfigMaps
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]

# Allow managing leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Allow managing events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

{{- if .Values.metrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-metrics-reader
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

{{- if .Values.metrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-metrics-reader
  labels:
    {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
