apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-config-operator.name" . }}-github
type: Opaque
data:
  token: {{ required "GitHub API token is required" .Values.github.apiToken | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-config-operator.name" . }}-webhook
type: Opaque
data:
  secret: {{ default (randAlphaNum 32) .Values.github.webhookSecret | b64enc }}
