# This rule is not used by the project push-github-secrets-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the qalisa.qalisa.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: push-github-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubsyncrepo-editor-role
rules:
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubsyncrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubsyncrepoes/status
  verbs:
  - get
