---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubactionsecretssyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubactionsecretssyncs/finalizers
  verbs:
  - update
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubactionsecretssyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubsyncrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubsyncrepoes/finalizers
  verbs:
  - update
- apiGroups:
  - qalisa.qalisa.github.io
  resources:
  - githubsyncrepoes/status
  verbs:
  - get
  - patch
  - update
