{{- if not .Values.github.privateKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-github
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: Opaque
data:
  private-key: {{ required "GitHub App private key is required when not using an existing secret" .Values.github.privateKey.explicit | b64enc }}
{{- end }}
