apiVersion: qalisa.qalisa.github.io/v1alpha1
kind: GithubActionSecretsSync
metadata:
  name: default
  namespace: gh-secret-operator
spec:
  secrets:
    - secretRef: gh-action
      key: API_KEY
    - secretRef: gh-action
      key: DB_PASSWORD
