apiVersion: v1
kind: Secret
metadata:
  name: test-github-secret
  namespace: default
type: Opaque
stringData:
  token: "test-github-token"
  # Add other test secrets as needed
  TEST_SECRET: "test-value-1"
  ANOTHER_SECRET: "test-value-2"
