//go:build !ignore_autogenerated

/*
Copyright 2025 Guillaume Vara.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionSecretsSync) DeepCopyInto(out *GithubActionSecretsSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionSecretsSync.
func (in *GithubActionSecretsSync) DeepCopy() *GithubActionSecretsSync {
	if in == nil {
		return nil
	}
	out := new(GithubActionSecretsSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubActionSecretsSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionSecretsSyncList) DeepCopyInto(out *GithubActionSecretsSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubActionSecretsSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionSecretsSyncList.
func (in *GithubActionSecretsSyncList) DeepCopy() *GithubActionSecretsSyncList {
	if in == nil {
		return nil
	}
	out := new(GithubActionSecretsSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubActionSecretsSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionSecretsSyncSpec) DeepCopyInto(out *GithubActionSecretsSyncSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionSecretsSyncSpec.
func (in *GithubActionSecretsSyncSpec) DeepCopy() *GithubActionSecretsSyncSpec {
	if in == nil {
		return nil
	}
	out := new(GithubActionSecretsSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubActionSecretsSyncStatus) DeepCopyInto(out *GithubActionSecretsSyncStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubActionSecretsSyncStatus.
func (in *GithubActionSecretsSyncStatus) DeepCopy() *GithubActionSecretsSyncStatus {
	if in == nil {
		return nil
	}
	out := new(GithubActionSecretsSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubSyncRepo) DeepCopyInto(out *GithubSyncRepo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubSyncRepo.
func (in *GithubSyncRepo) DeepCopy() *GithubSyncRepo {
	if in == nil {
		return nil
	}
	out := new(GithubSyncRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubSyncRepo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubSyncRepoList) DeepCopyInto(out *GithubSyncRepoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubSyncRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubSyncRepoList.
func (in *GithubSyncRepoList) DeepCopy() *GithubSyncRepoList {
	if in == nil {
		return nil
	}
	out := new(GithubSyncRepoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubSyncRepoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubSyncRepoSpec) DeepCopyInto(out *GithubSyncRepoSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubSyncRepoSpec.
func (in *GithubSyncRepoSpec) DeepCopy() *GithubSyncRepoSpec {
	if in == nil {
		return nil
	}
	out := new(GithubSyncRepoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubSyncRepoStatus) DeepCopyInto(out *GithubSyncRepoStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubSyncRepoStatus.
func (in *GithubSyncRepoStatus) DeepCopy() *GithubSyncRepoStatus {
	if in == nil {
		return nil
	}
	out := new(GithubSyncRepoStatus)
	in.DeepCopyInto(out)
	return out
}
