name: Release

on:
  push:
    #tags: ['v*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '1.23'
  HELM_VERSION: 'v3.12.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Prepare image metadata
        id: meta
        run: |
          echo "image_name=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT
          echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.image_tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ github.ref_name }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:cache,mode=max
          outputs: type=image,push=true

  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Update Helm documentation
        run: make helm-docs
      
      - name: Package Helm chart
        run: |
          helm package helm-charts/push-github-secrets-operator \
            --app-version ${GITHUB_REF#refs/tags/} \
            --version ${GITHUB_REF#refs/tags/v} \
            --destination .cr-release-packages
      
      - uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: .cr-release-packages/*.tgz

  create-release:
    needs: [build-and-push, publish-helm-chart]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: dist
      
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tgz
          generate_release_notes: true
          body: |
            Docker image: ${{ needs.build-and-push.outputs.image_tag }}