name: Release

on:
  push:
    branches:
      - main
    paths:
      - charts/github-actions-secrets-operator/Chart.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '1.23'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Prepare image metadata
        id: meta
        run: |
          echo "image_name=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT
          echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      
      - name: Read Chart.yaml
        id: chart
        run: |
          APP_VERSION=$(yq e '.appVersion' ./charts/${{ github.event.repository.name }}/Chart.yaml)
          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.image_tag }}
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:latest
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:${{ steps.chart.outputs.app_version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.chart.outputs.app_version }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.meta.outputs.image_name }}:cache,mode=max
          outputs: type=image,push=true

  publish-helm-chart:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Update Helm documentation
        run: make helm-docs
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
